br3ndonland/inboard

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/builds.yml
README.md

[GitHub Container Registry (GHCR) was released today](https://github.blog/2020-09-01-introducing-github-container-registry/)! :tada:
This PR will update the GitHub Actions workflow to push to GHCR instead of GitHub Packages.
The [migration](https://docs.github.com/en/packages/getting-started-with-github-container-registry/migrating-to-github-container-registry-for-docker-images) was simple:
- Update registry URLs from `docker.pkg.github.io` to `ghcr.io`
- Generate Personal Access Token (PAT) and use to authenticate to GHCR
- Update builds for GitHub Container Registry (71c9ddf)
- Update README for GitHub Container Registry (ebab152)
br3ndonland/inboard#5

Update GitHub Actions builds for GitHub Container Registry

---

.github/workflows/builds.yml
.github/workflows/tests.yml
README.md
poetry.lock
pyproject.toml

This commit will add test coverage tooling to inboard.
- Install [pytest-cov](https://github.com/pytest-dev/pytest-cov) for unit test coverage (b805360)
- **Configure pytest-cov in _pyproject.toml_** (308fd93): This commit will add pytest-cov configuration to _pyproject.toml_ using the [`addopts` key](https://docs.pytest.org/en/stable/reference.html#ini-options-ref). Note that `--cov-report=xml` will be used for CI only in the GitHub Actions workflows.
- **Configure pytest-cov for GitHub Actions** (76b4e38): XML reports will be generated by GitHub Actions for upload to [Codecov](https://docs.codecov.io/docs).
- **Upload [Codecov](https://docs.codecov.io/docs) reports with GitHub Actions** using [codecov/codecov-action](https://github.com/marketplace/actions/codecov) (2db56f9)
- **Add …

Add test coverage tooling

---

.github/CONTRIBUTING.md
README.md
inboard/__init__.py
inboard/app/base/main.py
inboard/app/utilities.py
inboard/gunicorn_conf.py
inboard/start.py
tests/app/test_main.py
tests/conftest.py
tests/test_start.py
tests/test_version.py

PR #7 added test coverage measurement with [pytest-cov](https://github.com/pytest-dev/pytest-cov) and [Codecov](https://codecov.io/). The initial coverage measurement showed 86% unit test coverage.
This PR will increase the unit test coverage to 100%.
- **Increase test coverage of inboard/`__init__.py`** (2a56650): 71% -> 100% coverage
- **Add unit tests for base ASGI app** (62d2e32, ed03219, 5e6af54): 0% -> 100% coverage
- Add unit tests for base ASGI app endpoints using Starlette TestClient
- Update base ASGI app with `PROCESS_MANAGER` environment variable
- Verify that `PROCESS_MANAGER` environment variable is set to either `"gunicorn"` or `"uvicorn"`
- Add unit test for exception when using inappropriate `PROCESS_MANAGER`
- Type-annotate base ASGI app instance as `Callable`
- …

Increase unit test coverage to 100%

---

README.md
inboard/app/base/main.py
inboard/gunicorn_conf.py
tests/conftest.py
tests/test_start.py

Unit test coverage is at 100%, but testing doesn't stop there. It is still important to test that the Uvicorn and Gunicorn servers are being properly configured with environment variables and configuration files. This PR will provide improvements to the unit tests for the Uvicorn and Gunicorn servers, while maintaining test coverage at 100%.
- **Properly mock Gunicorn and Uvicorn processes** (9ddbc4b)
- Add full process calls: verify that the server functions (`uvicorn.run` for Uvicorn, `subprocess.run` for Gunicorn) are called with expected arguments.
- Add mock for `subprocess.run()`: similar to Uvicorn update in 3906b3d.
- Provide Gunicorn with correct `worker_tmp_dir`: The Gunicorn server was previously exiting without need for a mock. However, this was actually because it couldn't …

Improve testing of server configuration

---

Dockerfile
pyproject.toml

[Poetry 1.1.0](https://github.com/python-poetry/poetry/releases/tag/1.1.0) is out! :tada: :clap: Among the notable changes is a move to [poetry-core](https://github.com/python-poetry/poetry-core) as the build backend.
This PR will update the _Dockerfile_ and _pyproject.toml_ for Poetry 1.1.0.
- **Update Dockerfile for Poetry custom installer** (94424ab):
- Installing Poetry via `pip` can lead to dependency conflicts, so the custom installer is recommended.
- There have been some issues adding Poetry's binaries to the `$PATH` in Docker. A manual symlink was needed (`ln -s $POETRY_HOME/bin/poetry /usr/local/bin`).
- Poetry now appears to be correctly added to the `$PATH` in Docker, so manual symlinking is no longer necessary.
- It is not essential to set `$POETRY_HOME`, but it will be done …

Update inboard for Poetry 1.1.0

---

.github/workflows/builds.yml
.github/workflows/codeql.yml
.github/workflows/hooks.yml
.github/workflows/tests.yml

GitHub Actions provides a set of [workflow commands](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions) to improve programmatic control over workflow steps. One useful command was `::set-env`, which sets environment variables for workflow jobs.
GitHub has [deprecated](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) `::set-env` due to a [moderate security vulnerability](https://github.com/actions/toolkit/security/advisories/GHSA-mfwh-5m23-j46w), and has provided updated syntax for working with [environment variables in workflows](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files).
```sh
echo "VARIABLE_NAME=value" >> …
```

Update GitHub Actions workflow syntax and Docker builds

---

.github/workflows/builds.yml
.github/workflows/hooks.yml
.github/workflows/tests.yml
Dockerfile
README.md

This project started with Python 3.8. Python 3.9 is now available. so the _Dockerfile_ and GitHub Actions workflows have been updated to Python 3.9.
It is helpful to retain support for Python 3.8, as some Python packages and software stacks have not yet been updated for Python 3.9. This PR will add support for multiple Python versions, starting with 3.8.
- Add Python version matrices for GitHub Actions (1a7a5ad)
- Add Python version build argument to Dockerfile (69ebc5f)
- Build Docker images for multiple Python versions (dc8da18)
- Add info on specifying Python version to README (c14de7f)
- Use Python version matrix in Docker job (465c923)
br3ndonland/inboard@d9734b4
br3ndonland/inboard@6f01d75

Support multiple Python versions

---

Dockerfile
inboard/app/main_fastapi.py
inboard/app/main_starlette.py
inboard/app/utilities_fastapi.py
inboard/app/utilities_starlette.py
poetry.lock
pyproject.toml

FastAPI depends on Starlette. For simplicity, inboard was set up to install FastAPI from the get-go, because installing FastAPI will also install Starlette. However, this means that the Starlette application is dependent on FastAPI, which is sort of backwards. Within the inboard source code, the utilities module contained the HTTP Basic Auth implementations for Starlette and FastAPI, but because FastAPI was imported into that module, it also meant that the Starlette application required FastAPI in order to import the module.
This PR will improve the separation of concerns between FastAPI and Starlette, so that the FastAPI and Starlette features are independent, and the Starlette application can run without installing FastAPI.
- Separate FastAPI and Starlette utilities (a9d5617)
- Separate …

Improve separation between FastAPI and Starlette

---

.vscode/launch.json
README.md
inboard/start.py
poetry.lock
pyproject.toml
tests/test_start.py

This PR will implement the Uvicorn `reload_dirs` setting, enabling file watching and hot-reloading with [watchgod](https://github.com/samuelcolvin/watchgod) for development.
[watchgod](https://github.com/samuelcolvin/watchgod) is a filesystem watcher that was added in [Uvicorn 0.11.4](https://github.com/encode/uvicorn/releases/tag/0.11.4). The directories to watch can be configured from the command-line with the `--reload-dir` argument. Multiple `--reload-dir`s can be used, with one directory specified each time.
The Uvicorn docs say, "If you're running using programmatically, using `uvicorn.run(...)`, then use equivalent keyword arguments," but this is not quite accurate for `--reload-dir`. The programmatic equivalent is `reload_dirs`, which accepts `List[str]`.
To implement …

Implement Uvicorn reload_dirs

---

README.md

This PR will add a logo for the project.
The logo was created with [Figma](https://www.figma.com/), based on the following resources (in the order in which they are seen in the image, top to bottom):
- [GitHub: FastAPI](https://github.com/tiangolo/fastapi)
- [GitHub: Starlette](https://github.com/encode/starlette)
- [GitHub: Uvicorn](https://github.com/encode/uvicorn)
- [Wikimedia: Gunicorn](https://commons.wikimedia.org/wiki/File:Gunicorn_logo_2010.svg)
- [Wikimedia: Python](https://commons.wikimedia.org/wiki/File:Python_logo_and_wordmark.svg)
- [Wikimedia: Docker (container engine)](https://commons.wikimedia.org/wiki/File:Docker_%28container_engine%29_logo.svg)
SVG images can't be uploaded within GitHub comments, so the SVG has been added to a [public GitHub …

Add inboard logo

---

.github/CONTRIBUTING.md
.github/workflows/builds.yml
.github/workflows/codeql.yml
.github/workflows/hooks.yml
.github/workflows/tests.yml

In August 2020, [GitHub announced](https://github.blog/changelog/2020-08-26-set-the-default-branch-for-newly-created-repositories/) that the default branch for new repositories will change from `master` to `main`. To enable branch name changes for existing repositories, they [enabled branch renaming from the web UI](https://github.blog/changelog/2021-01-19-support-for-renaming-an-existing-branch/), and provided some [guidelines for renaming `master` to `main`](https://github.com/github/renaming). Renaming the branch from the web UI doesn't rename references to the branch, such as in GitHub Actions workflows, so this needs to be done with separate commits. Also note, for repos with GitHub Pages sites, the sites may display a `404` after renaming the default branch from `master` to `main` …

Rename master branch to main

---

.github/workflows/builds.yml

[GitHub Actions](https://docs.github.com/en/actions/guides/building-and-testing-python), [Poetry](https://python-poetry.org/docs/), and [pytest](https://docs.pytest.org/en/latest/) have helped to automate Python testing and Docker builds in this repo. It is simple to test API endpoints _before_ the Docker images are built, using pytest and the [Starlette/FastAPI `TestClient`](https://fastapi.tiangolo.com/tutorial/testing/) as seen in _[test_main.py](https://github.com/br3ndonland/inboard/blob/develop/tests/app/test_main.py)_, but it is also important to test the API endpoints in the Docker images _after_ the images are built. These are commonly called "smoke tests." The inboard repo doesn't yet have automated smoke tests.
After the Docker images are built in GitHub Actions and pushed to …

Add Docker smoke tests

---

README.md
inboard/start.py
tests/conftest.py
tests/test_start.py

The project previously had a [`mock_logger` pytest fixture in _conftest.py_](https://github.com/br3ndonland/inboard/blob/bb088ac/tests/conftest.py#L144) that instantiated a root logger with `logging.getLogger()`. The individual log level attributes were then patched, like `mocker.patch.object(logger, "debug")`. This was problematic, because Mypy thought that the logger didn't have these attributes, requiring frequent `# type: ignore[attr-defined]` comments.
The solution is to patch the root logger object [where it is looked up](https://docs.python.org/3/library/unittest.mock.html#where-to-patch), from `inboard.start.logging`. [About 2000 lines into `logging/__init__.py`](https://github.com/python/cpython/blob/b32d8b4/Lib/logging/__init__.py#L1920), there is a module level object `root` …

Properly mock logger

---

Dockerfile

The inboard start script was previously run by a [`CMD` with shell notation](https://docs.docker.com/engine/reference/builder/#cmd) in the _Dockerfile_.
```dockerfile
CMD python /app/inboard/start.py
```
This worked, but could have been more flexible.
This PR will modify the command used to run the start script in Docker.
```dockerfile
ENTRYPOINT ["python"]
CMD ["-m", "inboard.start"]
```
- Declare the Python executable in an [`ENTRYPOINT`](https://docs.docker.com/engine/reference/builder/#entrypoint), with the "exec form" (the array syntax, which is preferred).
- Use `CMD` to pass arguments to the Python executable. This allows the arguments to be overridden, so that the file path can still be used instead of the module path if desired.
Use of the module path in this way is dependent on …

Use module path for start script in Dockerfile

---

inboard/start.py
tests/test_start.py

The core logic for running the Uvicorn and Gunicorn+Uvicorn servers is located in _[start.py](https://github.com/br3ndonland/inboard/blob/develop/inboard/start.py)_. The `start.start_server()` method is what actually starts the servers. Gunicorn and Uvicorn are configured differently, so the `start.start_server()` method ended up getting quite complex in order to handle these differences.
This PR will refactor the configuration options passed to Gunicorn and Uvicorn into separate functions. The result is a start script with the same programming API and almost exactly the same line length, but improved readability and separation of concerns.
- Refactor Gunicorn and Uvicorn options into separate functions, `start.set_gunicorn_options()` and `start.set_uvicorn_options()`.
- Remove …

Refactor start script to improve organization of Gunicorn and Uvicorn server settings

---

.github/workflows/builds.yml
.vscode/launch.json
README.md
inboard/app/main_starlette.py
inboard/app/utilities_fastapi.py
inboard/app/utilities_starlette.py
tests/app/test_main.py
tests/conftest.py

The HTTP Basic auth methods have been useful as examples, but they could also be used by other applications when the inboard Python package has been installed. This PR will provide some updates to these methods.
The only potentially breaking change is that the default `BASIC_AUTH_USERNAME` and `BASIC_AUTH_PASSWORD` will be removed. These environment variables must be set on the server to use HTTP Basic auth.
**Update HTTP Basic auth for FastAPI and Starlette** (2630dea)
- Remove default username and password (**IMPORTANT**): the environment variables `BASIC_AUTH_USERNAME` and `BASIC_AUTH_PASSWORD` must now be set on the server to use HTTP Basic auth. Defaults were provided as examples, but in production contexts, the defaults shouldn't be used.
- Raise an exception if server HTTP Basic …

Update HTTP Basic auth for FastAPI and Starlette

---

README.md
inboard/__init__.py

In Python, the [`__all__` object](https://docs.python.org/3/reference/simple_stmts.html#the-import-statement) is a sequence (typically a list or tuple) that defines the _public names_ of a module or package. When other applications install the package, the objects corresponding to the _public names_ are exposed for direct import and use.
This pull request will add `__all__`, defining the public API of the package. To start, the public API will consist of a few useful utilities that are commonly imported in other Python applications, such as the logging configuration logic and HTTP Basic auth implementations.
There are some technical limitations to keep in mind when setting up `__all__`. For example, this project defines optional dependencies, including FastAPI and Starlette. If objects …

Add __all__ with public names

---

poetry.lock
pyproject.toml

[FastAPI 0.65](https://github.com/tiangolo/fastapi/releases/tag/0.65.0) now supports [Starlette 0.14](https://github.com/encode/starlette/releases/tag/0.14.0), which unblocks the issue described in #20, bbd9e61, and 12eef2a.
- Upgrade to FastAPI 0.65 and Starlette 0.14 (92326a2)
br3ndonland/inboard#20
br3ndonland/inboard@bbd9e61
br3ndonland/inboard@12eef2a

Upgrade to FastAPI 0.65 and Starlette 0.14

---

.github/workflows/builds.yml
Dockerfile
docs/docker.md

This PR will add support for [Alpine Linux](https://alpinelinux.org/), based on the distribution provided by the [official Python Docker images](https://hub.docker.com/_/python).
- Add support for Alpine Linux to Dockerfile (c7d83e7)
- Add support for Alpine Linux to GitHub Actions (a442b9f)
- Document support for Alpine Linux (41ae8b6)
tiangolo/uvicorn-gunicorn-docker#19
tiangolo/uvicorn-gunicorn-docker#22
tiangolo/uvicorn-gunicorn-docker#33
tiangolo/uvicorn-gunicorn-docker#45
tiangolo/uvicorn-gunicorn-docker#65
tiangolo/uvicorn-gunicorn-docker#72
tiangolo/uvicorn-gunicorn-fastapi-docker#18
tiangolo/uvicorn-gunicorn-fastapi-docker#31
tiangolo/uvicorn-gunicorn-fastapi-docker#53
tiangolo/uvicorn-gunicorn-fastapi-docker#61

Add support for Alpine Linux

---

.github/workflows/builds.yml
Dockerfile
docs/docker.md

This PR will add support for the "slim" variant of the [official Python Docker images](https://hub.docker.com/_/python), which reduces the Debian Linux environment to the minimal runtime needed for Python.
- Add support for Debian slim Docker images (582dcef)
- Document how to use Debian slim Docker images (9389572)
br3ndonland/inboard#37
tiangolo/uvicorn-gunicorn-docker#16
tiangolo/uvicorn-gunicorn-docker#61
tiangolo/uvicorn-gunicorn-docker#72
tiangolo/uvicorn-gunicorn-fastapi-docker#61
tiangolo/uvicorn-gunicorn-fastapi-docker#71

Add support for Debian slim Docker images

---

docs/environment.md
inboard/start.py
poetry.lock
pyproject.toml
tests/test_start.py

PR #21 implemented the Uvicorn `reload_dirs` setting, enabling file watching and hot-reloading with [watchgod](https://github.com/samuelcolvin/watchgod) for development.
In encode/uvicorn#820 and [Uvicorn 0.15](https://github.com/encode/uvicorn/releases/tag/0.15.0), additional reload configuration options were added:
- `reload_delay` (CLI equivalent: `--reload-delay`)
- `reload_excludes` (CLI equivalent: `--reload-exclude`)
- `reload_includes` (CLI equivalent: `--reload-include`)
This PR will implement the new Uvicorn reload options. The options will be configured with the following environment variables:
- `RELOAD_DELAY`
- `RELOAD_EXCLUDES`
- `RELOAD_INCLUDES`
- Upgrade to Uvicorn 0.15 (ffb47df)
- Implement new Uvicorn 0.15 reload config options (f4428dd)
- Document new Uvicorn 0.15 …

Upgrade to Uvicorn 0.15 and implement new reload options

---

docs/environment.md
inboard/start.py
tests/conftest.py
tests/test_start.py

Gunicorn supports a `GUNICORN_CMD_ARGS` catch-all environment variable for [configuring settings](https://docs.gunicorn.org/en/stable/settings.html). It looks for the `GUNICORN_CMD_ARGS` environment variable automatically, and gives these settings precedence over other environment variables and Gunicorn config files.
It would be useful to have something similar for Uvicorn. This PR will add support for a `UVICORN_CONFIG_OPTIONS` environment variable. The idea here is to allow a catch-all Uvicorn config variable in the spirit of `GUNICORN_CMD_ARGS`, so that advanced users can specify the full range of Uvicorn options even if inboard has not directly implemented them. The `inboard.start` module will run the `UVICORN_CONFIG_OPTIONS` environment variable value through `json.loads()`, and then …

Add `UVICORN_CONFIG_OPTIONS` environment variable for catch-all configuration

---

docs/contributing.md

adminstrators => administrators
This repository needs:
A couple typo fixes in docs/contributing.
Line 246 adminstrators => administrators
Line 250 adminstrators => administrators
The commits in this pull request will:
Fix two typos in docs/contributing.

Found some typos while browsing the docs.

---

.github/workflows/builds.yml
.github/workflows/hooks.yml
.github/workflows/tests.yml
Dockerfile

Poetry has introduced a number of problematic changes recently. To help buffer against these problematic changes, this PR will implement installation and testing of specific versions of Poetry, rather than the latest version.
The following steps will be taken to verify the Poetry version, both when installing Poetry on the GitHub Actions runner, and when installing Poetry in Docker container images:
1. Set the `POETRY_VERSION` environment variable, which should be used by the _get-poetry.py_ and _install-poetry.py_ install scripts to install the specified version
2. Download the Poetry install script from the GitHub repo at a specific Git tag by templating the `POETRY_VERSION` environment variable into the URL
3. Run a shell test to assert that the Poetry version returned by the `poetry …

Pin and test Poetry version

---

docs/environment.md
docs/logging.md
inboard/__init__.py
inboard/logging_conf.py
tests/test_logging_conf.py
tests/test_start.py

When applications with APIs are deployed, it is common to perform "health checks" on them. Health checks are usually performed by making HTTP requests to a designated API endpoint. These checks are made at frequent intervals, and so they can fill up the access logs with large numbers of unnecessary log records.
To avoid logging health checks, it would be helpful to have a way to filter health checks out of the logs.
This PR will add a configurable logging filter to `inboard.logging_conf`.
- Filters can be provided as a comma-separated string with the environment variable `LOG_FILTERS`, like `LOG_FILTERS="/health, /heartbeat"`.
- The environment variable value will be converted into a set of strings.
- Each log message will then be checked for each filter in the set. If any matches are …

Add configurable logging filter

---

.github/workflows/builds.yml
.github/workflows/codeql.yml
.github/workflows/hooks.yml
.github/workflows/tests.yml
Dockerfile
inboard/app/main_base.py
inboard/app/utilities_starlette.py
inboard/gunicorn_conf.py
inboard/logging_conf.py
inboard/start.py
tests/app/test_main.py
tests/test_gunicorn_conf.py

This PR will add [Python 3.10](https://docs.python.org/3/whatsnew/3.10.html) support to inboard.
- [What's new in Python 3.10](https://docs.python.org/3/whatsnew/3.10.html)
- [actions/python-versions 3.10.0](https://github.com/actions/python-versions/releases/tag/3.10.0-117470)
- actions/setup-python#249
- Python versions must now be quoted in YAML. `3.10` (without quotes) is interpreted as a float and becomes `3.1`, so `"3.10"` must be used instead.
- https://github.com/actions/setup-python/issues/249#issuecomment-934299359
- https://dev.to/hugovk/the-python-3-1-problem-85g
<details><summary>Expand this details element for details on some of the problems seen with <em>get-poetry.py</em> and <em>install-poetry.py</em> on Python 3.10.</summary>
The previous _get-poetry.py_ install script …

Add Python 3.10 support

---

.github/workflows/builds.yml
Dockerfile
docs/contributing.md
docs/docker.md

This PR will update Docker builds to use BuildKit, a next-generation build back-end that can be used with front-ends including `buildctl`, `docker`, and `docker buildx`.
BuildKit supports some helpful [features](https://github.com/moby/buildkit/blob/HEAD/frontend/dockerfile/docs/syntax.md), including:
- **Heredocs**: [here-documents](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_07), also known as "heredocs," allow multiple lines of text to be passed into a shell command. Heredoc support was added to Dockerfiles in the [1.4.0 release](https://github.com/moby/buildkit/releases/tag/dockerfile%2F1.4.0). This feature enables Dockerfile `RUN` commands to be written like shell scripts, instead of having to jam commands into long run-on lines.
- `COPY --link`, …

Use BuildKit for Docker builds

---

pyproject.toml

Uvicorn lumps several optional dependencies into a "standard" extra:
- `colorama` (for Windows)
- `httptools`
- `python-dotenv`
- `pyyaml`
- `uvloop`
- `watchgod`/`watchfiles` (`watchgod` was renamed to `watchfiles`)
- `websockets`
There has been some discussion about the drawbacks of this approach:
- encode/uvicorn#219
- encode/uvicorn#1274
- encode/uvicorn#1547
inboard has previously installed the "standard" extra by default.
This PR will change the default to installing Uvicorn without "standard." This is a **BREAKING CHANGE** to inboard's dependencies.
A new `inboard[uvicorn-fast]` extra will be added for dependencies from `uvicorn[standard]` related to web server performance, and can be installed by specifying the extra when installing inboard, like `python -m pip install …

Break up `uvicorn[standard]` optional dependencies

---

.github/workflows/ci.yml
.github/workflows/codeql.yml
Dockerfile
docs/docker.md
pyproject.toml

This PR will add [Python 3.11](https://docs.python.org/3/whatsnew/3.11.html) support to inboard.
- Add Python 3.11 to GitHub Actions workflows
- Add Python 3.11 classifier to _pyproject.toml_
- Set Python 3.11 as default version in _Dockerfile_
- inboard will now run tests with Python 3.11, in addition to 3.8-3.10
- inboard will now build and publish its PyPI package using Python 3.11
- inboard will now include a Python 3.11 classifier in its PyPI package
- inboard will now ship Docker images running Python 3.11, in addition to 3.8-3.10, and Docker images tagged with `latest` will now use 3.11
Related projects that have released support for Python 3.11 include, in alphabetical order:
- [FastAPI 0.86.0](https://github.com/tiangolo/fastapi/releases/tag/0.86.0) (2022-11-03)
- [Hatch …

Add Python 3.11 support

---

.github/workflows/ci.yml
.github/workflows/codeql.yml
Dockerfile
docs/docker.md
pyproject.toml

This PR will add [Python 3.12](https://docs.python.org/3/whatsnew/3.12.html) support to inboard.
- Add Python 3.12 to GitHub Actions workflows
- Add Python 3.12 classifier to _pyproject.toml_
- Set Python 3.12 as default version in _Dockerfile_
- inboard will now run tests with Python 3.12, in addition to 3.8-3.11
- inboard will now build and publish its PyPI package using Python 3.12
- inboard will now include a Python 3.12 classifier in its PyPI package
- inboard will now ship Docker images running Python 3.12, in addition to 3.8-3.11, and Docker images tagged with `latest` will now use 3.12
Related projects that have released support for Python 3.12 include:
- AnyIO ([4.0.0 - 2023-08-30](https://github.com/agronholm/anyio/releases/tag/4.0.0))
- FastAPI([0.109.0 - …

Add support for Python 3.12

---

.github/workflows/ci.yml

On 2023-06-14, Docker updated the default Debian Linux version in its Python official images from Debian bullseye to Debian bookworm. As inboard uses the default Debian Linux version from the Docker Python official images, this meant that the next release of inboard (0.50.0 - 2023-06-22) automatically updated to bookworm. There were some [issues](https://github.com/docker-library/python/issues?q=bookworm) noted by the community after this update.
inboard will now specify the Debian version when building Docker images. The current Debian version is still Debian 12 ("bookworm"). The next Debian version, Debian 13 ("trixie") does not have a release date yet, but inboard will update to trixie when it is stable and will provide a new release after the update.
- …

Specify Debian version
